const ActionTypes = {
  SET_ERROR: 'SET_ERROR',
  START_TITLES: 'START_TITLES',
  SET_TITLES: 'SET_TITLES',
  SET_CURRENT_FILM: 'SET_CURRENT_FILM',
  START_FILM_DETAILS: 'START_DETAILS',
  SET_FILM_DETAILS: 'SET_FILM_DETAILS',
  SET_REVIEW_MODE: 'SET_REVIEW_MODE',
  CLEAR_REVIEW_MODE: 'CLEAR_REVIEW_MODE',
};

export default ActionTypes;
